name: basezf
recipe: lamp
config:
  webroot: public

services:
  database:
    portforward: 33062
  node:
    type: node:12.13
    build:
      - "cd $LANDO_MOUNT && npm install"

tooling:
  node:
    service: node
  npm:
    service: node
